apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb-water-filter
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true
    jsonData:
      version: Flux
      organization: disertatie
      defaultBucket: water_filter
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
    editable: true
