# Imaginea oficiala + configuratia "coapta" in imagine.
# Pe Fargate nu exista disc local de montat, ca in docker-compose.
FROM eclipse-mosquitto:2.1.2

COPY config/mosquitto.conf /mosquitto/config/mosquitto.conf
